---

- name: current shell
  shell: >
    echo $SHELL | grep "{{ which_zsh }}"
  register: current_shell
  ignore_errors: True
  changed_when: False


- debug: msg="{{ current_shell.stdout }}"

- name: grep shells
  shell: >
    cat /etc/shells | grep "{{ which_zsh }}"
  register: grep_shells 
  ignore_errors: True
  when: current_shell|failed

- name: append shells
  become: yes
  shell: >
    echo {{ which_zsh }} >> /etc/shells
  when: ( current_shell|failed ) and
        ( grep_shells.rc != 0 )

- name: change login shell
  shell: >
    chpass -s {{ which_zsh }}
  register: result
  until: result.rc == 0
  retries: 3
  when: current_shell|failed
