---

- name: Ensure configured taps are tapped.
  homebrew_tap: "tap={{ item }} state=present"
  with_items: "{{ homebrew_taps }}"

- name: Install packages
  homebrew: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('latest') }}
  with_items: "{{ homebrew_installed_packages }}" 

- name: cask パッケージをインストール
  homebrew_cask: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('installed') }}
  with_items: "{{ homebrew_cask_apps }}"
